name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm test
      run: npm test
      env:
        CI: true
        TEST_SUITE: test
    
#      env: CXX=g++-4.8 TEST_SUITE=coveralls
#     env: CXX=g++-4.8 TEST_SUITE=lint
